[package]
name = "arctic"
version = "0.1.0"
authors = ["Ian Goldberg <iang@uwaterloo.ca>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curve25519-dalek = "2"
rand = "0.7"
sha2 = "0.9"
itertools = "0.12"
rayon = "1"
